name: Manual Workflow

on:
  workflow_dispatch:
    inputs: 
      name:
        description: 'Enter your name'
        type: string
        default: 'test'
      age:
        description: 'Enter your age'
        type: number
        required: true
      gender:
        description: 'Enter your gender'
        type: choice
        options:
          - Male
          - Female
      married:
        description: 'Are you Married?'
        type: boolean

jobs:
  actions:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"

      - name: Age
        run: echo "${{ inputs.age }}"

      - name: Gender
        run: echo "${{ inputs.gender }}"

      - name: Married
        run: echo "${{ inputs.married }}"
